### ISSUE TITLE
北京线下小聚会~开源人才招聘主题

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/open-source-best-practice#100]
本次线下聚会由 @LinuxSuRen 发起。

大家可以参考下面的话题来交流：
* 开源商业化公司的开源人才招聘
  * 招聘渠道
  * 人才考核标准
* 任何开源相关
  * 吐槽
  * 有趣的经历
  * 个人体验
  * 困惑
* 其他

时间：周末，待定
地址：北京朝阳广顺南大街16号嘉美中心写字楼30层
形式：待定

## 报名方法：
* 在帖子后面留言（表示要报名即可）
* 加 @LinuxSuRen 微信，进微信群

## 鸣谢
* 感谢**声网**为本次活动提供场地及点心赞助

## 注意事项：
* 这次活动没有人数预期，没有预期达成任何目标
* 活动费用以 AA 制为主，如有赞助的话，费用会平均减少
* 活动没有演讲要求，但也欢迎有兴趣的同学来个快闪分享、交流
* 以圆桌交流为主（可能是大圆桌或小圆桌，根据具体场地以及大家意愿等情况来定）

> 如果您有合适的（距离适中、免费、可以容纳 10 人左右、夏季有空调），欢迎联系 @LinuxSuRen ，或者直接在下面添加回复。
> 上次活动 https://github.com/opensource-f2f/episode/discussions/145 是 @LinuxSuRen 上次发起的 AA 制聚会活动。

**Comment by MikeyWei** [comment]
赞，线下交流或聚会，还是有相对明确的话题比较好。

**Comment by Tango2018cc** [comment]
北京望京的 8km coffee（有共享办公区域） 地方不错，有包间可供10-20人闲聊

**Comment by LinuxSuRen** [comment]
@Tango2018cc 周六来约吗

**Comment by Tango2018cc** [comment]
阔以，就在我家附近，我去蹭个会

**Comment by LinuxSuRen** [comment]
> 阔以，就在我家附近，我去蹭个会

您加下我微信（同 GitHub），拉到一个群里，方便到时候沟通。

**Comment by Licae** [comment]
关注好久了，终于可以参加啦

**Comment by Licae** [comment]
与主题无关可以参加嘛，关注挺久的啦

**Comment by YeSuX** [comment]
上海有活动吗？上海的同学也想参加

**Comment by LinuxSuRen** [comment]
> 上海有活动吗？上海的同学也想参加

有机会去上海了，我一定发起一下。当然，在上海的朋友，也欢迎在这里发活动。

**Comment by pengpeng** [comment]
报名参加

**Comment by LinuxSuRen** [comment]
感谢各位的支持，很开心认识了一些新朋友！
