### ISSUE TITLE
开源之夏 2022 非正式对话（北京站）

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/open-source-best-practice#113]
## 背景
Hackathon 可能是每一位程序员都喜欢的编程活动，而 Rick 作为体验过多次 Google Summer of Code 这种全球性开源编程活动的开源爱好者，深切地感受到了这种活动的巨大魅力。因此，当看到国内也能有中立性的大型开源编程活动时，倍感兴奋，这简直就是开源爱好者（尤其对于开源参与经验不多的朋友们）与开源社区之间的盛筵。开源之夏进入第三年，每一年都迈出了不大但坚实的前进脚步，在不断的积累中，开源之夏将越来越多的高校学生和开源社区联结起来，也帮助高校学生逐渐成长为开源世界的星星之火。

开源之夏同样也希望通过不同的方式展现学生参与活动过程中及结项后的成果价值，在《开源之夏专访》这个栏目中，已经有 30 多位优秀的 contributor 以公开的形式分享他们的参与经验和成果。他们分布在不同的城市，甚至有些同学在海外求学，将这种差异不吝啬地聚集和展现出来，也正是开源的魅力吧！不过，文字分享之外，还有更多精彩。只不过也许是没有意识到除了代码以外，开源还有更多有趣的地方；也许是觉得自己成长不显著，不好意思拿出来说；也许觉得发不发这类文章也无关紧要。

但是，Community Over Code！人与人之间通过交流、互动，从而实现互帮互助、共同成长，才是我们更希望在开源社区中看到的。线下面对面的交流，更是有助于大家增强对开源的认识、理解，每一位关注开源之夏的开源爱好者也可以互通有无。在此，Rick 以个人的身份来获得了开源之夏官方对活动的认可，以召集参与开源之夏活动的同学们、社区 mentor、开源爱好者，一起聊开源。

## 活动日程
- 自我介绍环节 
  - 参与者自我介绍，限时 2 分钟
- 休息 5 分钟，进入正式环节
-  对话环节
  -   自由发言：开源之夏中遇到的高光时刻及开源吐槽
  -   展望期待：开源之夏能为参与者带来什么
  -   建言献策：对开源之夏的建议
- 开放型问题：
  -  考虑成立开源之夏城市站的可行性

## 参与指南
本次活动**旨在**发挥桥梁的作用，了解到身在最一线的社区 mentor、学生等的真实体验、反馈，帮助开源之夏变得越来越好。我们非常期待每一位参与过、想要参与到开源之夏的社区 mentor、学生来参加我们的活动。

- 地点：北京海淀区中关村微软大厦 1 号楼，天安门会议室
- 时间：11 月 19 号（周六），下午 2 ～ 6 点

[点击此处报名](https://wj.qq.com/s2/11072594/1036/)。

## FAQ
* Q：我没参与过开源之夏，可以参与到本次活动吗？
* A：非常欢迎，这将会一次极好的深入了解开源之夏的机会。
* Q：一个开源社区，可以来多少人？
* A：考虑到疫情、场地限制，每个社区有 1～2 个参与名额。
* Q：是否考虑社区、企业合作？
* A：这是一次个人发起的活动，没有社区、企业的合作环节，但欢迎给本次活动提供各种形式的支持，包括：活动转发、物品等；但是，不会有传统活动的 Logo 展示。

## 鸣谢
- 微软的场地赞助（陈阳、周鹏飞的场地协助）
- 开源之夏的周边赞助（书包、T恤）
- Miya 赞助三本《拥抱开源》
- 古思为赞助三本《开源之迷》
- Rick 赞助零度可乐一提
- 李梦赞助零食包一份
- ALC Beijing 周边纪念币、T恤

**Comment by LinuxSuRen** [comment]
报名二维码

![download](https://user-images.githubusercontent.com/1450685/199201108-c6a4510e-b3e3-4c4f-b513-c063061b4139.png)

**Comment by cyx0928** [comment]
Hey，我们的项目在这里：[https://github.com/illa-family。](https://github.com/illa-family%E3%80%82)
我们想赞助ILLA产品的体恤等周边。

**Comment by wujicong** [comment]
华为开源，赞助15件卫衣
昇思MindSpore，赞助10件T恤

- 我们的项目：
华为开源：https://www.huawei.com/cn/open-source
昇思MindSpore：https://mindspore.cn/

**Comment by hobo0cn** [comment]
[PrimiHub](https://github.com/primihub) 开源社区赞助3个保温杯和鼠标垫若干，欢迎大家关注：）

**Comment by LinuxSuRen** [comment]
@wey-gu 个人赞助的三本书已收到
<img src="https://user-images.githubusercontent.com/1450685/199917959-ef1235bb-ecb2-4078-9155-9a242e0888f7.png" width="450">

**Comment by LinuxSuRen** [comment]
@wey-gu 个人赞助的三本书已收到
<img src="https://user-images.githubusercontent.com/1450685/200100294-9688b500-75a5-401e-b681-24a052461b0e.png" width="450">

**Comment by LinuxSuRen** [comment]
今收到华为开源，赞助15件卫衣，感谢 @wujicong

![image](https://user-images.githubusercontent.com/1450685/201519691-bd37643a-5444-4808-8c01-1d5367ed47db.png)

**Comment by LinuxSuRen** [comment]
各位，本周三晚 8 点会有一次针对本场活动的头脑风暴，我们可以就以下内容做交流、讨论：

* 周边礼品如何发放（预计，物品数量>=人数）
* 活动环节创意
* 在活动当天希望讨论的话题（本次会议，不会展开）
* 当天可能会有部分同学无法到场，我们改如何解决线上线下同步

https://meeting.tencent.com/dm/YUeKKOjhGVk2

**Comment by LinuxSuRen** [comment]
头脑风暴会议录屏 https://www.bilibili.com/video/BV1MR4y1f79W/?spm_id_from=333.999.0.0&vd_source=ca1041974e9b44975cc4d5355ad7001f

**Comment by LinuxSuRen** [comment]
周六无法参与线下活动的同学，欢迎到时候用腾讯会议接入（下午两点开始）

https://meeting.tencent.com/dm/hxfvag425EQz

**Comment by LinuxSuRen** [comment]
各位关注到这个活动的朋友们，考虑到北京疫情的影响，我们本次活动延期举行（上面的在线会议同样延后）。具体日期还请继续关注。

**Comment by LinuxSuRen** [comment]
今收到 MindSpore 的 T恤 5 件、防晒服 5 件、大号鼠标垫 10 件

感谢 @wujicong

**Comment by LinuxSuRen** [comment]
本次活动，由于年前疫情影响推迟。

现重新开放，时间为 3 月 4 日，地点是中关村创业大街-6号楼

**Comment by LinuxSuRen** [comment]
活动成功举办，感谢各位的热情和支持！

**Comment by LinuxSuRen** [comment]
![1678096624981](https://user-images.githubusercontent.com/1450685/223077304-9d635d3c-623d-4b4f-b8f1-599860e38deb.png)
![image](https://user-images.githubusercontent.com/1450685/223077359-67d40096-a17a-48e9-abb8-3e3d1855f86d.png)

**Comment by LinuxSuRen** [comment]
![image](https://user-images.githubusercontent.com/1450685/223077537-c2927279-d2bb-46c4-86f4-3b0468c6bf48.png)
![image](https://user-images.githubusercontent.com/1450685/223077565-13721a96-2cb9-455f-a0fd-f230286d4a94.png)

**Comment by LinuxSuRen** [comment]
开源之夏官网对本次活动的报道

https://summer-ospp.ac.cn/news/detail/269?order=updateTime
