### ISSUE TITLE
开源之夏 2023 Community Bond（北京站）

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/open-source-best-practice#129]
在 23 年开源之夏正式编码环节开始之前，潜在的 contributor 与社区之间的互动将会是非常重要的一个环节。希望通过一场线下活动可以增强开发者与项目、社区、mentor 之间的相互了解。

> 在活动正式开始前，文中所有内容都有机会更新、改变，欢迎提出您的创新。

## 日程
* 暖场
  * 开源爱好者的视频播放
  * @wu-sheng 吴晟
  * @chengleqi 程乐齐
  * @webup 张海立
  * Richard 
  * @tisonkun
* 主题分享
  * 携手前行，开源之夏第四年 - 李梦/开源之夏品牌负责人
  * 如何选择优质的开源项目开启社区“实习”旅程 - 周鹏飞/微软Azure产品经理，CNCF project maintainer
  * 与 Apache Doris 社区一同成长 - 鲁大师（Apache Doris Committer）
  * Apache ShardingSphere 在开源之夏 - 赵锦超（Apache  ShardingSphere Committer）
  * 轻松玩转 Alluxio—开源之旅启程 - 丁博文/Alluxio 开源团队工程师
  * 企业端如何看待寻找并激发学生参与开源 - 张驰/AFFiNE 联合创始人&CTO 
* 闪电演讲（3分钟，严格限时）
  * 小燕
  * 田俊
  * 温祖彤
  * 王坤山
  * 刘聪
  * 王嘉树
  * 唐晓敏
* 分享自己的 PR（或 issue）故事（5~10 分钟）
* TBD（测试驱动开发）演示

## 报名
* 本次活动主要面向社区 contributor、mentor，高校学生、老师，以及一切关心开源的个人、企业、组织
* 预期人数：40

## 时间
5 月 7 日（周日），下午 1~5 点

## 场地
北京市海淀区（五道口）大通成府公馆150号楼（智源大厦）6 层

本次场地由奇绩创坛提供赞助！

## 鸣谢
* Apache Doris 社区提供周边礼品
* GreptimeDB 社区提供周边礼品
* Apache ShardingSphere 社区提供周边礼品
* Thoughtworks 提供技术协作手册
* 华为开源提供 T恤
* 开源之夏官方提供的 T恤、背包
* AFFiNE 赞助 20 本《JavaScript 的 20 年》

## 其他
* [上次活动](https://github.com/LinuxSuRen/open-source-best-practice/issues/113)
* [原始文档](https://docs.qq.com/doc/DYUV5YXlHWE14em9X?u=e93a39da6c9a41cf953b58bedc3d0f5e)
* [公众号推文](https://mp.weixin.qq.com/s/SUkk1NNojLrjURmrcrvtWQ)

**Comment by luzhijing** [comment]
您好，Apache Doris 社区希望参与到本次活动中来，我们可以赞助马克杯、T恤、徽章以及贴纸等周边礼品。

这是我们的项目地址 [https://github.com/apache/doris](https://github.com/apache/doris)

**Comment by xtang** [comment]
您好，GreptimeDB 社区也希望可以参与到本次活动中，可以赞助马克杯、贴纸、T 恤和帆布包等周边。
我们项目地址是 https://github.com/greptimeteam/greptimedb
谢谢。

**Comment by zhaojinchao95** [comment]
您好，Apache ShardingSphere 社区希望参与到本次活动中来，我们可以赞助T恤、 ShardingSphere 海外书等周边礼品。
这是我们的项目地址 https://github.com/apache/shardingsphere

**Comment by LinuxSuRen** [comment]
来自 Thoughtworks 赞助的技术写作手册若干本

![0f16c8222bacafa5fa4101a58c5e504](https://user-images.githubusercontent.com/1450685/233237231-228961bd-7c85-4db4-87a3-0cdc44a1efa8.jpg)

**Comment by wu-sheng** [comment]
@LinuxSuRen 这是录制的视频，因为是腾讯会议，似乎会有水印

https://drive.google.com/file/d/10gKdDVHgPIMfDUq7lVjba24_87Hle1rg/view?usp=sharing

**Comment by LinuxSuRen** [comment]
非常感谢 @wu-sheng 对本次活动的大力支持。
考虑到视频需要稍微处理下，我会处理后再放出来。下面是 @wu-sheng 的视频留言

![image](https://user-images.githubusercontent.com/1450685/233257697-1527de05-5174-427a-a488-9b6ac6102069.png)

**Comment by LinuxSuRen** [comment]
非常感谢 @wu-sheng 对本次活动的大力支持。
考虑到视频需要稍微处理下，我会处理后再放出来。下面是 @wu-sheng 的视频留言

![image](https://user-images.githubusercontent.com/1450685/233260733-ee2ca984-54e9-4d44-8e21-434518188868.png)

**Comment by LinuxSuRen** [comment]
交流备选议题：
* 如何躲避 KPI 类或完成任务时的项目

**Comment by chengleqi** [comment]
@LinuxSuRen 我录制了一段视频，讲述了下自己参加开源之夏活动的经历～
https://drive.google.com/file/d/14Q2O7t7ANUFomtlt7Oh_0XQNX9wOOnpZ/view?usp=share_link

**Comment by chengleqi** [comment]
> @LinuxSuRen 我录制了一段视频，讲述了下自己参加开源之夏活动的经历～ https://drive.google.com/file/d/14Q2O7t7ANUFomtlt7Oh_0XQNX9wOOnpZ/view?usp=share_link

这是国内的地址： https://cowtransfer.com/s/a3eb1db236a441

**Comment by LinuxSuRen** [comment]
感谢 Richard 给大家带来的视频
https://drive.google.com/file/d/1Kx3Q8xmBRcMQZ_Q0wDMSf5t_cCOXbsNp/view

**Comment by LinuxSuRen** [comment]
[开源之夏PPT模板.pptx](https://github.com/LinuxSuRen/open-source-best-practice/files/11410816/PPT.pptx)

**Comment by LinuxSuRen** [comment]
感谢 @tisonkun 的视频 https://drive.google.com/file/d/108BkR4WBJ386HoMxX1XauoquUjN-RxKd/view?usp=sharing

**Comment by LinuxSuRen** [comment]
很开心能与各位交流！期待下次活动！

![image](https://user-images.githubusercontent.com/1450685/236679939-edaaa6cf-c06c-46ce-a732-000bb9064c22.png)

**Comment by LinuxSuRen** [comment]
本次活动的视频回放

【开源之夏 2023 线下交流会 · 北京站】 https://www.bilibili.com/video/BV1PT411b7jo/?share_source=copy_web&vd_source=1e8d9e70686a4845fa44f8d3f5ff7925
