### ISSUE TITLE
将开源最佳实践翻译成英文

### ISSUE THREAD

**Issue by JohnNiang** [LinuxSuRen/open-source-best-practice#18]
我们希望能够提供一个英文版的开源最佳实践，来帮助到全球的开发者们顺利入门开源协作。

**Comment by LinuxSuRen** [comment]
@JohnNiang 考虑到你是 https://github.com/halo-dev/halo 这个项目的主要维护者之一，不知道是否可以把这个仓库加到项目 halo 的 issues 和 PR 的模板中呢，当然是目前智能加到中文的模板中。

另外，这个最佳实践也可以有一个列表，列出来那些对这个最佳实践认可的项目。

也希望能得到 @ruibaby 的反馈！

**Comment by ruibaby** [comment]
@LinuxSuRen Okay，我会和 @JohnNiang 一起讨论一下。

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen Okay，我会和 @JohnNiang 一起讨论一下。

非常感谢

**Comment by ruibaby** [comment]
已经添加：

- https://github.com/halo-dev/halo/issues/new?assignees=&labels=bug&template=bug_report.zh.yml
- https://github.com/halo-dev/halo/issues/new?assignees=&labels=&template=feature_request.zh.yml

**Comment by wjsvec** [comment]
@LinuxSuRen
我试着翻译了一下这一段，不知道这样的质量是不是可行？

## Get started
仔细阅读项目自述文件（README），遵循贡献指南（CONTRIBUTION）中给出的流程。

面对一个新的项目，尤其是在相对不熟悉的领域，有如下的方法可以帮助你提供前期的贡献：
* 文档贡献，这是非常有效的一种了解项目的方式，通常我们可以在阅读文档的过程中，修复一些错别字、标点符号、语法错误、无效链接等等
* good-first-issues，对于希望收到更多贡献的项目而言，会在一些容易上手的 issues 上添加该标签

## Get started 
Please read the project README carefully, and the process in the CONTRIBUTION.

In the early days of a new project, especially in an unfamiliar field, here are some ways to help you contribute to an open-source project.
* Document contributions, this is a very effective way to learn about a project. Usually, we can fix typos, punctuation, grammatical errors, broken links, and so on as we read the document.
* good-first-issue, for projects that want to receive more contributions, the tag will be added to issues that are easy to fix.

**Comment by LinuxSuRen** [comment]
@wjsvec 非常赞👍。我先把 https://github.com/LinuxSuRen/open-source-best-practice/pull/24 这个合并进去，你再帮忙把上面的这段补充上。
