### ISSUE TITLE
开源来为简历增色有不有什么建议？

### ISSUE THREAD

**Issue by M-M-dot** [LinuxSuRen/open-source-best-practice#81]
老师，我是今天上课的同学吧。我以前没有做过开源。想问一问，我想通过开源来为简历增色，寻找offer的话。有什么建议和途径推荐嘛？

**Comment by LinuxSuRen** [comment]
hi @M-M-dot ，很高兴能和你交流该话题。
首先，在不少的情况下，面试的结果会与企业的偏好以及面试官的风格有非常大的关系。假设这几个因素固定的话，可以从如下的几点考虑：

* 你提交的代码贡献（包括代码规范度、注释、逻辑、单元测试）是否能体现你的技术功底，以及 PR 在 review 过程中的沟通情况（这里能体现到你协作能力）
* 你提交的文档贡献，可以体现到你的文案能力、文字表达能力、英文能力等
* 你在开源社区（项目）参与的深度，是否参加过例会，是否有某种形式得到过社区的认可，是否在社区里做过分享等等

说白了，能帮你增色的地方非常多，但前提有两个：做的是否深入、目标企业是否认可这种形式。

**Comment by Satohchen** [comment]
我的理解，参与开源项目的贡献对于给工作简历增色，就犹如你做一份实习，更具知名度的实习单位、对口的实习岗位角色、以及你在实习过程中完成的优质工作内容，都能帮助你的简历更容易通过筛选，帮助招聘者通过你的实习经历看出你与应聘岗位的能力匹配度。
所以，如果你参与开源项目的目标是希望为工作简历加分，那你在挑选开源项目、参与开源工作内容以及对于整个过程，就应该像你找实习、保持做实习工作一样的态度，只有努力付出不会骗人，当然选择也很重要。

**Comment by LinuxSuRen** [comment]
鉴于没有更多讨论，先关闭该 issue
