### ISSUE TITLE
立一个 flag，当 star 数到 200 时，来一次直播与对参与开源感兴趣的朋友们互动

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/open-source-best-practice#91]
希望看到这个直播的朋友，可以在下面留言！（可以关注我的视频号）

<img src="https://user-images.githubusercontent.com/1450685/172031054-51101abb-9e5c-4926-94c2-22bee365ce71.jpg" width="300px"></img>

**Comment by donhui** [comment]
star 199 了，马上就该开直播了 😄

**Comment by LinuxSuRen** [comment]
> star 199 了，马上就该开直播了 😄

是该兑现了。有兴趣直播来聊吗？可以节后安排起来。

**Comment by minhanghuang** [comment]
到了到了

**Comment by LinuxSuRen** [comment]
正在征集直播嘉宾，近期会放出来议题、时间。感谢各位的关注！

**Comment by LinuxSuRen** [comment]
10 月 15 日（周六）晚 8 点，我会和 @ichengxinxin 大家在视频号上直播交流一些开源实践，欢迎各位关注上面的视频号。也非常欢迎感兴趣的朋友们连麦。

有任何想交流的话题，可以在这个 issue 下留言。再次感谢各位对开源的关注！

**Comment by LinuxSuRen** [comment]
Some bad cases:

* https://v2ex.com/t/887117

**Comment by LinuxSuRen** [comment]
活动结束，感谢各位的支持！
